name: 'Conveyor Maven Template'
on: [workflow_call]
jobs:
  maven-compile:
    id: compile
    runs-on: ubuntu-latest
    env:
      MAVEN_COMPILE_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end -Dstyle.color=always"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn ${MAVEN_COMPILE_CLI_OPTS} compile
        shell: bash
      - run: mvn ${MAVEN_COMPILE_CLI_OPTS} install
  
  maven-tests:
    runs-on: ubuntu-latest
    env:
      MAVEN_COMPILE_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end -Dstyle.color=always"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn ${MAVEN_COMPILE_CLI_OPTS} install
        shell: bash
    needs: [compile]