name: 'Conveyor Maven Template'
on: [workflow_call]

generic-maven: &generic-maven
  runs-on: ubuntu-latest
  env:
    MAVEN_COMPILE_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end -Dstyle.color=always"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
jobs:
  maven-compile:
    <<: *generic-maven
    # runs-on: ubuntu-latest
    # env:
    #   MAVEN_COMPILE_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end -Dstyle.color=always"
    steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/cache@v1
    #     with:
    #       path: ~/.m2/repository
    #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #       restore-keys: |
    #         ${{ runner.os }}-maven-
      - run: mvn ${MAVEN_COMPILE_CLI_OPTS} compile
        shell: bash
  
  maven-tests:
    runs-on: ubuntu-latest
    env:
      MAVEN_COMPILE_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end -Dstyle.color=always"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn ${MAVEN_COMPILE_CLI_OPTS} install
        shell: bash
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            ./target
            ./*/target
    needs: [maven-compile]